### ISSUE TITLE
Update Port to datamodel 2.0.0 spec

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#102]
According to datamodel 2.0.0 draft spec, a port could be described (almost) like so:

```json
{
    "id": "urn:sdx:port:amlight.net:s3:s3-eth4",
    "name": "s3-eth4",
    "node": "urn:sdx:node:amlight.net:s3",
    "type": "100GE",
    "mtu": 9000,
    "status": "up",
    "state": "enabled",
    "nni": "",
    "services": {
        "l2vpn-ptp": {
            "vlan_range": [[1,4000]]
        },
        "l2vpn-ptmp": {
            "vlan_range": [[1,1000], [2000,3000]]
        }
    },
    "private": ["state", "mtu"]
}
```

Issue #81 and PR #88 added the capability to parse/validate this.  As a follow-up, `Port` has to carry `services` attribute.

**Comment by sajith** [comment]
I believe that implementing this depends on https://github.com/atlanticwave-sdx/datamodel/issues/92.

**Comment by sajith** [comment]
Also depends on #95.

**Comment by italovalcy** [comment]
Hi @sajith, awesome you catched this! Like you mentioned, it would be nice if we can leverage the services vlan_range attribute instead of label_range (which is not even defined on the data model spec).  Thanks for documenting this issue!

**Comment by italovalcy** [comment]
Another one I just found: Port.short_name is not defined on the Data model spec. I think we should remove this attribute, unless you see an use case for it.

**Comment by YufengXin** [comment]
Related to the issue in sdx-controller regarding user specified vlan in connection request:
https://github.com/atlanticwave-sdx/sdx-controller/issues/232

1. the port.services.vlan_range has been implemented in the parser.
2. the port.vlan_range is still being used to accommodate existing available unittest. Maybe we should repurpose/rename this for user specified vlan in connection request. @italovalcy 

-> consolidate between these two.
