### ISSUE TITLE
Port object should also include the type attribute form Topology Spec 2.0

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/datamodel#139]
Hi,

According to the Topology Data model spec 2.0.0, the Port object has the `type` attribute as described below:

> The type attribute represents the technology and bandwidth of the physical port (or interface). type is an enum with only one value acceptable. The Topology data model specification supports only Ethernet. The type enum is 100FE, 1GE, 10GE, 25GE, 40GE, 50GE, 100GE, 400GE, and Other. When the value Other is chosen, no bandwidth guaranteed services will be supported in this port. The value Other was created to enable flexibility when the port is not on the enum. In case Other becomes recurrent, the SDX team must increase the specification subversion and add the correct bandwidth to the type enum. The specification version table must be updated with such info.

**Comment by italovalcy** [comment]
We do have some references to the `port_v2.json` testing data on PR #121 but I believe that it ended up being left behind:

https://github.com/atlanticwave-sdx/datamodel/blame/312996abf3ffec61f736fb8ac171e9eaebb764a3/tests/__init__.py#L37

That file does not exists on https://github.com/atlanticwave-sdx/datamodel/tree/312996abf3ffec61f736fb8ac171e9eaebb764a3/tests/data

**Comment by YufengXin** [comment]
Yes. And, in operation, matching port types, esp. on the NNI link is important. It's a known underimplemented issue.  Good timing to address it.
