### ISSUE TITLE
Invalid v1.0 format connection request

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#150]
This one is less useful because it (1) asks for a VLAN that is not present on the ingress port, and (2) asks for a range on the egress port while not asking for a matching range on the ingress port.

https://github.com/atlanticwave-sdx/datamodel/blob/fde0abe1f961ec9b7652bbedffd99acf6ebf3e38/src/sdx_datamodel/data/requests/test_request-amlight_zaoxi-p2p-v2.json#L4-L12

Note that the label range available on "urn:sdx:port:amlight.net:A1:3" is "100-200" and "1000":

https://github.com/atlanticwave-sdx/datamodel/blob/fde0abe1f961ec9b7652bbedffd99acf6ebf3e38/src/sdx_datamodel/data/topologies/amlight_user_port.json#L315-L319

[Service Provisioning Data Model 1.0 specification](https://sdx-docs.readthedocs.io/en/latest/specs/provisioning-api-1.0.html#mandatory-attributes) says this: "If one endpoint has the VLAN range or option “all”, all endpoints must have the same value."

**Comment by YufengXin** [comment]
https://github.com/atlanticwave-sdx/pce/issues/227

And updated the test request json
