### ISSUE TITLE
Error when running `pytest`

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#33]
Output when running `python -m unittest` is a little noisy, so it might be useful to be able to run `pytest`.  There's an error when running `pytest` though:

```
$ python -m pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-report --cov-report term-missing
  inifile: [..]/datamodel/setup.cfg
  rootdir: [..]/datamodel
```

Arguments to pytest are coming from `setup.cfg`, which we probably don't need:

https://github.com/atlanticwave-sdx/datamodel/blob/3f99454f232416a3c4fa66355c74ade13478c529/setup.cfg#L4-L5

**Comment by sajith** [comment]
I figured that I need to install [pytest-cov](https://pypi.org/project/pytest-cov/) for `pytest` to work as intended here, following the hints here:

https://github.com/atlanticwave-sdx/datamodel/blob/3f99454f232416a3c4fa66355c74ade13478c529/setup.cfg#L30-L33

Seems that:

1. pytest-runner is [deprecated](https://pypi.org/project/pytest-runner/), so that should probably go.
2. That syntax of writing `tests_require` is probably incorrect.  It should be:
```
tests_require=
        pytest-cov
```
3. But pytest-runner recommends removing `setup_requires` and `tests_require` in favor of something like Tox.
4. Python is moving towards specifying packages with `pyproject.toml` ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 612](https://peps.python.org/pep-0621/)) anyway.

I'll investigate if we can use `pyproject.toml` here.

**Comment by YufengXin** [comment]
There is a 'pyproject.toml' in the PCE module. You could also test over there.
