### ISSUE TITLE
Consolidate models from all AtlanticWave SDX projects

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#51]
The three places where we keep our models currently could easily become a source of confusion and chaos:

- https://github.com/atlanticwave-sdx/datamodel/tree/develop/sdxdatamodel/models
- https://github.com/atlanticwave-sdx/sdx-lc/tree/main/swagger_server/models
- https://github.com/atlanticwave-sdx/sdx-controller/tree/main/swagger_server/models

This repository should ideally hold all models, and the other projects should use them.

Related: atlanticwave-sdx/sdx-lc#50 and atlanticwave-sdx/sdx-controller#35

**Comment by YufengXin** [comment]
in #144
